cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'
urlpatterns = [
    path('', views.car_list_all, name='car_list_all'),
    path('sall/', views.car_list_all_secret, name='car_list_all_secret'),
    path('<int:car_id>/', views.details, name='car_details'),
    path('add/', views.car_create, name='car_create'),
    path('delete/<int:car_id>/', views.car_delete, name='car_delete'),
    path('edit/<int:car_id>/', views.car_edit, name='car_edit'),


]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_view, name='home_view'),
    path('ukaz/', views.ukaz_view, name='ukaz_view'),
]

wawelska/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('cars/', include('cars.urls'), name='cars'),
    path('admin/', admin.site.urls, name='admin'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cars/models.py
from django.db import models


class Car(models.Model):
    car_number = models.SmallIntegerField(
        blank=True,
        null=True,
        verbose_name='Numer pojazdu'
    )
    car_name = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        default='',
        verbose_name='Marka i model'
    )
    car_mileage = models.PositiveIntegerField(
        blank=True,
        null=True,
        verbose_name='Przebieg'
    )
    car_service_inspection_date = models.DateField(
        blank=True,
        null=True,
        verbose_name='Data przeglądu serwisowego'
    )
    car_technical_inspection_date = models.DateField(
        blank=True,
        null=True,
        verbose_name='Data przeglądu technicznego',
    )
    car_content = models.TextField(
        blank=True,
        null=True,
        verbose_name='opis'
    )
    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        related_name='cars',
        blank=True,
        null=True,
    )

    def __str__(self):
        return f'{self.car_number}'

users/models.py
from django.db import models


class User(models.Model):
    user_name = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )
    user_phone_number = models.PositiveIntegerField(
        blank=True,
        null=True
    )

    def __str__(self):
        return f'Imie: {self.user_name} numer: {self.user_phone_number}'

cars/forms.py
from django.forms import ModelForm
from cars.models import Car


class CarForm(ModelForm):
    class Meta:
        model = Car
        exclude = ['car_name']
        help_texts = {
            'car_service_inspection_date': 'Uzyj formatu: YYYY-MM-DD',
            'car_technical_inspection_date': 'Uzyj formatu: YYYY-MM-DD',
        }

cars/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from cars.forms import CarForm
from cars.models import Car
from datetime import date, timedelta


def check_inspection_date(delta_days):
    warning_alert = date.today() + timedelta(days=delta_days)
    danger_alert = date.today()
    return warning_alert, danger_alert


def car_list_all(request):
    cars = Car.objects.all()
    warning_alert, danger_alert = check_inspection_date(delta_days=30)
    return render(
        request=request,
        template_name='cars/car_list_all.html',
        context={
            'cars': cars,
            'warning_allert': warning_alert,
            'danger_alert': danger_alert
        }
    )


def car_list_all_secret(request):
    cars = Car.objects.all()
    warning_alert, danger_alert = check_inspection_date(delta_days=30)
    return render(
        request=request,
        template_name='cars/car_list_all_secret.html',
        context={
            'cars': cars,
            'warning_allert': warning_alert,
            'danger_alert': danger_alert
        }
    )


@login_required()
def details(request, car_id):
    car = Car.objects.get(pk=car_id)

    return render(
        request=request,
        template_name='cars/car_details.html',
        context={
            'car': car
        }
    )


@login_required()
def car_create(request):
    car_form = CarForm(request.POST or None)

    if car_form.is_valid():
        car_form.save()
        return redirect('cars:car_list_all')

    return render(
        request=request,
        template_name='cars/car_form.html',
        context={
            'car_form': car_form,
            'edit': False
        }
    )


@login_required()
def car_edit(request, car_id):
    car = Car.objects.get(pk=car_id)
    car_form = CarForm(
        data=request.POST or None,
        files=request.FILES or None,
        instance=car)

    if car_form.is_valid():
        car_form.save()
        return redirect('cars:car_list_all')

    return render(
        request=request,
        template_name='cars/car_form.html',
        context={
            'car_form': car_form,
            'edit': True,
            'car': car
        }
    )


@login_required()
def car_delete(request, car_id):
    car = Car.objects.get(pk=car_id)
    if request.method == 'POST':
        car.delete()
        return redirect('cars:car_list_all')

    return render(
        request=request,
        template_name='cars/car_delete.html',
        context={
            'car': car
        }
    )

home/views.py
from django.shortcuts import render


def home_view(request):
    return render(
        request=request,
        template_name='home/home.html',
    )

def ukaz_view(request):
    return render(
        request=request,
        template_name='home/ukaz.html'
    )

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

</head>
<body>


    {% include 'includes/header.html' %}

    {% block content %}
    {% endblock %}

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

templates/cars/car_delete.html
{% extends 'base.html' %}

{% block title %} Usuń pojazd {{ car.car_number }} {% endblock %}

{% block content %}
    <div class="container">
        Czy napewno chcesz usunąć pojazd nr {{ car.car_number }}?
        <p></p>
        <div class="btn-group">
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">USUŃ</button>
        </form>
        </div>

        <div class="btn-group">
            <a href="{% url 'cars:car_list_all' %}">
                <button type="button" class="btn btn-primary">COFNIJ</button>
            </a>
        </div>
    </div>

{% endblock %}

templates/cars/car_details.html
{% extends "base.html" %}

{% block title %} {{ car.car_number }} {% endblock %}

{% block content %}
    <div class="container mt-3">
        <table class="table">
            <tr>
                <th>NUMER WEWNĘTRZNY</th>
                <td>{{ car.car_number }}</td>
            </tr>
            <tr>
                <th>PRZEBIEG</th>
                <td>{{ car.car_mileage }}</td>
            </tr>
            <tr>
                <th>DATA PRZEGLĄDU SERWISOWEGO</th>
                <td>{{ car.car_service_inspection_date }}</td>
            </tr>
            <tr>
                <th>DATA PRZEGLĄDU TECHNICZNEGO</th>
                <td>{{ car.car_technical_inspection_date }}</td>
            </tr>
            <tr>
                <th>OPIS</th>
                <td>{{ car.car_content }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

templates/cars/car_form.html
{% extends "base.html" %}

{% block title %}
    {% if edit is False %}
        Dodaj pojazd
    {% else %}
        Edytuj pojazd {{ car.car_number }}
    {% endif %}
{% endblock %}

{% block content %}

    {% load crispy_forms_tags %}
        <div  class="container">
            <form method="POST">
                {% csrf_token %}

                {% for f in car_form %}
                    {{ f|as_crispy_field }}
                {% endfor %}

                {% if edit is False %}
                    <button type="submit" class="btn btn-success">DODAJ</button>
                {% else %}
                    <button type="submit" class="btn btn-success">EDYTUJ</button>
                {% endif %}

            </form>
        </div>

{% endblock %}

templates/cars/car_list_all.html
{% extends 'base.html' %}

{% block title %} Cars {% endblock %}

{% block content %}
    {{ dt }}
    <div class="container">

        <table class="table table-hover">
            <thead>
            <tr>
                <th>NUMER WEWNĘTRZNY</th>
                <th>PRZEBIEG</th>
                <th>DATA PRZEGLĄDU SERWISOWEGO</th>
                <th>DATA PRZEGLĄDU TECHNICZNEGO</th>
                <th>OPCJE</th>
            </tr>
            </thead>
            <tbody>
                {% for car in cars %}
                <tr>
                    <td>{{ car.car_number }}</td>
                    <td>{{ car.car_mileage }}</td>
                    {% if car.car_service_inspection_date < danger_alert %}
                        <td class="table-danger">{{ car.car_service_inspection_date }}</td>
                    {% elif car.car_service_inspection_date < warning_allert%}
                        <td class="table-warning">{{ car.car_service_inspection_date }}</td>
                    {% else %}
                        <td>{{ car.car_service_inspection_date }}</td>
                    {% endif %}

                    {% if car.car_technical_inspection_date < danger_alert %}
                        <td class="table-danger">{{ car.car_technical_inspection_date }}</td>
                    {% elif car.car_technical_inspection_date < warning_allert%}
                        <td class="table-warning">{{ car.car_technical_inspection_date }}</td>
                    {% else %}
                        <td>{{ car.car_technical_inspection_date }}</td>
                    {% endif %}
                    <td>
                        <a href="{% url 'cars:car_details' car.id %}">
                            <button type="button" class="btn btn-success header_button_link"><i class="bi bi-eye"></i></button>
                        </a>

                        <a href="{% url 'cars:car_edit' car.id %}">
                            <button type="button" class="btn btn-primary header_button_link"><i class="bi bi-pencil-square"></i></button>
                        </a>

                        <a href="{% url 'cars:car_delete' car.id %}">
                            <button type="button" class="btn btn-danger"><i class="bi bi-trash-fill"></i></button>
                        </a>
                    </td>
                </tr>

                {% endfor %}
    </tbody>
  </table>

    <div class="d-flex justify-content-end">
            <a class="header_button_link" href="{%  url 'cars:car_create' %}">
                <button type="button" class="btn btn-success add_button header_button_link">DODAJ</button>
            </a>
    </div>
    </div>



{% endblock %}

templates/cars/car_list_all_secret.html
{% extends 'base.html' %}

{% block title %} Cars {% endblock %}

{% block content %}
    {{ dt }}
    <div class="container">

        <table class="table table-hover">
            <thead>
            <tr>
                <th>MARTKA I MODEL</th>
                <th>NUMER WEWNĘTRZNY</th>
                <th>PRZEBIEG</th>
                <th>DATA PRZEGLĄDU SERWISOWEGO</th>
                <th>DATA PRZEGLĄDU TECHNICZNEGO</th>
                <th>OPCJE</th>
            </tr>
            </thead>
            <tbody>
                {% for car in cars %}
                <tr>
                    <td>{{ car.car_name }}</td>
                    <td>{{ car.car_number }}</td>
                    <td>{{ car.car_mileage }}</td>
                    {% if car.car_service_inspection_date < danger_alert %}
                        <td class="table-danger">{{ car.car_service_inspection_date }}</td>
                    {% elif car.car_service_inspection_date < warning_allert%}
                        <td class="table-warning">{{ car.car_service_inspection_date }}</td>
                    {% else %}
                        <td>{{ car.car_service_inspection_date }}</td>
                    {% endif %}

                    {% if car.car_technical_inspection_date < danger_alert %}
                        <td class="table-danger">{{ car.car_technical_inspection_date }}</td>
                    {% elif car.car_technical_inspection_date < warning_allert%}
                        <td class="table-warning">{{ car.car_technical_inspection_date }}</td>
                    {% else %}
                        <td>{{ car.car_technical_inspection_date }}</td>
                    {% endif %}
                    <td>
                        <a href="{% url 'cars:car_details' car.id %}">
                            <button type="button" class="btn btn-success header_button_link"><i class="bi bi-eye"></i></button>
                        </a>

                        <a href="{% url 'cars:car_edit' car.id %}">
                            <button type="button" class="btn btn-primary header_button_link"><i class="bi bi-pencil-square"></i></button>
                        </a>

                        <a href="{% url 'cars:car_delete' car.id %}">
                            <button type="button" class="btn btn-danger"><i class="bi bi-trash-fill"></i></button>
                        </a>
                    </td>
                </tr>

                {% endfor %}
    </tbody>
  </table>

    <div class="d-flex justify-content-end">
            <a class="header_button_link" href="{%  url 'cars:car_create' %}">
                <button type="button" class="btn btn-success add_button header_button_link">DODAJ</button>
            </a>
    </div>
    </div>



{% endblock %}

templates/home/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}


{% endblock %}

templates/home/ukaz.html
{% extends 'base.html' %}

{% block title %} Ukaz {% endblock %}

{% block content %}

    {% load static %}
    <img src="{% static 'img/ukaz.jpg' %}" alt="ukaz">

{% endblock %}

templates/includes/header.html
<!-- Navbar -->

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'home:home_view' %}"><i class="bi bi-house" style="font-size: 2rem;"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'cars:car_list_all' %}"><i class="bi bi-car-front" style="font-size: 2rem;" ></i></a>
            </li>
        </ul>

            {% if user.is_authenticated %}
                <a class="header_button_link" href="{% url 'logout' %}">
                    <button type="button" class="btn btn-danger  header_button_btn">WYLOGUJ</button>
                </a>
            {% else %}
                <a class="header_button_link" href="{% url 'login' %}">
                    <button type="button" class="btn btn-warning  header_button_btn">ZALOGUJ</button>
                </a>

            {% endif %}

    </div>

</nav>